# Generated by Django 3.1.7 on 2021-03-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='code',
            new_name='conf_code',
        ),
    ]
