# Generated by Django 3.1.7 on 2021-03-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210315_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='valid_until',
            field=models.DateTimeField(blank=True),
        ),
    ]
