# Generated by Django 3.1.7 on 2021-03-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(null=True, to='distributor.Tag'),
        ),
    ]
